// Unity Build Uber File generated by CMake
// This file is auto generated, do not manually edit it.

#include <StdAfx.h>
#include <F:/Crytek/CryEnginePrototype/Code/GamePlugin.cpp>
#include <F:/Crytek/CryEnginePrototype/Code/MathExtension.cpp>

